trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  solutionPath: 'SimpleAPISln.sln'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/tests/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
  
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish --configuration $(buildConfiguration) --output --configuration $(Build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    #projects: 'src/app/Simple.API/Simple.API.csproj'
    projects: $(solutionPath)
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'